name: flower_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  injectable: ^2.5.1
  get_it: ^7.6.4
  retrofit: ^4.7.2
  logger: ^2.3.1
  json_annotation: ^4.9.0
  dio: ^5.6.0
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  pinput: ^5.0.1
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_otp_text_field: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  mockito: ^5.4.4
  loading_indicator: ^3.1.1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.7.5
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constant/
  filename: app_assets.dart
  field_prefix:
  ignore_comments: true
  classname: AppAssets
