name: flower_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  another_flushbar: ^1.12.32
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  get_it: ^8.2.0
  retrofit: ^4.2.0 # Specify a compatible version
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_otp_text_field: null
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.14
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get: ^4.7.2
  get_it: ^8.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  image_picker: ^1.2.0
  injectable: ^2.5.1
  intl: any
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  loading_indicator: ^3.1.1
  location: ^8.0.1
  webview_flutter: ^4.9.0 # Specify a version
  fluttertoast: ^8.2.14
  another_flushbar: ^1.12.32
  get: ^4.7.2
  firebase_auth: 
  cloud_firestore: 
  firebase_messaging: 
  firebase_storage: 

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0 # Specify a version
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0 # Downgraded to avoid conflict
  mockito: ^5.4.4 # Downgraded as suggested

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constant/
  filename: app_assets.dart
  field_prefix: null
  ignore_comments: true
  classname: AppAssets
