name: flower_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  get_it: ^8.2.0
  retrofit:
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  pinput: ^5.0.1
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_otp_text_field:
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.2.0
  mockito: ^5.4.4  
  loading_indicator: ^3.1.1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2

  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/json/
   

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf