name: flower_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: null
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.5.1
  intl: any
  json_annotation: ^4.9.0
  logger: null
  path_provider: ^2.1.5
  pinput: ^5.0.1
  retrofit: null
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: null
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_18pt-Regular.ttf
        - asset: assets/font/Inter_18pt-Medium.ttf
        - asset: assets/font/Inter_18pt-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constant/
  filename: app_assets.dart
  field_prefix: null
  ignore_comments: true
  classname: AppAssets
